// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermarketMock;

#nullable disable

namespace SupermarketMock.Migrations
{
    [DbContext(typeof(SupermarketContext))]
    [Migration("20260702055300_AddWishlist")]
    partial class AddWishlist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupermarketMock.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SupermarketMock.Models.CartItem", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaximumDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int?>("UsageLimitPerUser")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("SupermarketMock.Models.CouponCategory", b =>
                {
                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("CouponId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CouponCategories");
                });

            modelBuilder.Entity("SupermarketMock.Models.CouponProduct", b =>
                {
                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CouponId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CouponProducts");
                });

            modelBuilder.Entity("SupermarketMock.Models.CouponUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountApplied")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("CouponId", "UserId");

                    b.ToTable("CouponUsages");
                });

            modelBuilder.Entity("SupermarketMock.Models.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("SupermarketMock.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SnowflakeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CouponId");

                    b.HasIndex("SnowflakeId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SupermarketMock.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<long>("SnowflakeId")
                        .HasColumnType("bigint");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SnowflakeId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Description = "Whole milk 1L",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Fresh Milk",
                            Photo = "5c9a09e3-bba9-4882-9c78-a95cfe277fb5.jpg",
                            Price = 22.90m,
                            SnowflakeId = 317625235773855528L,
                            StockQuantity = 120,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 6,
                            Description = "Fresh baked bread",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Whole Wheat Bread",
                            Photo = "24d4616d-8770-4706-a302-3c46ecb89bf7.jpg",
                            Price = 18.50m,
                            SnowflakeId = 317625235773854947L,
                            StockQuantity = 80,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Description = "Farm fresh eggs",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Large Eggs (10pcs)",
                            Photo = "17a7f4e4-d5ae-4451-8095-ec961535cefa.jpg",
                            Price = 28.00m,
                            SnowflakeId = 317625235773856039L,
                            StockQuantity = 65,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Sweet Japan Fuji apple",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Red Apple",
                            Photo = "7729457e-fd10-4a1e-9e43-24297319bd63.jpg",
                            Price = 15.90m,
                            SnowflakeId = 317625235773857742L,
                            StockQuantity = 200,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Philippine banana",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Banana",
                            Photo = "5bc69672-d4cb-47d9-9f58-7b62c4986212.jpg",
                            Price = 12.90m,
                            SnowflakeId = 317625235773855304L,
                            StockQuantity = 150,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "500g boneless",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chicken Breast",
                            Photo = "cce4d49f-ee37-497c-872f-b2c91e7498ea.jpg",
                            Price = 48.00m,
                            SnowflakeId = 317625235773856174L,
                            StockQuantity = 45,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Classic coke",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Coca Cola 1.25L",
                            Photo = "9b74ea07-2055-4174-8941-453c19ff04e4.jpg",
                            Price = 9.90m,
                            SnowflakeId = 317625235773855812L,
                            StockQuantity = 90,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Original flavor",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Potato Chips",
                            Photo = "f7f649aa-b373-44ba-88ef-1f23b3349a2e.jpg",
                            Price = 14.50m,
                            SnowflakeId = 317625235773854539L,
                            StockQuantity = 110,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 12,
                            Description = "Thailand long grain",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "White Rice 5kg",
                            Photo = "38c41e9b-6e7c-4427-8f42-4fd77f15ce49.jpg",
                            Price = 45.00m,
                            SnowflakeId = 317625235773856987L,
                            StockQuantity = 60,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Fresh red tomato",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Tomato",
                            Photo = "022ef28e-cfee-4010-93d7-c023bc82fd6a.jpg",
                            Price = 8.90m,
                            SnowflakeId = 317625235773854504L,
                            StockQuantity = 180,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "150g cup",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Strawberry Yogurt",
                            Photo = "7d046f01-f1ed-4c56-a514-f9636cfb3579.jpg",
                            Price = 7.90m,
                            SnowflakeId = 317625235773856480L,
                            StockQuantity = 95,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "200g fresh salmon",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Salmon Fillet",
                            Photo = "8054b103-f09d-4e9b-8d59-750569bde198.jpg",
                            Price = 89.00m,
                            SnowflakeId = 317625235773857309L,
                            StockQuantity = 30,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "1L 100% juice",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Orange Juice",
                            Photo = "fa02abc3-5c99-4111-8054-f4b666ef66ea.jpg",
                            Price = 19.90m,
                            SnowflakeId = 317625235773854823L,
                            StockQuantity = 70,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 9,
                            Description = "500ml tub",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Ice Cream Vanilla",
                            Photo = "068f7754-cf3d-4267-b024-0db2d6888daf.jpg",
                            Price = 35.00m,
                            SnowflakeId = 317625235773854877L,
                            StockQuantity = 55,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 11,
                            Description = "Colgate 100g",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Toothpaste",
                            Photo = "d6a5391b-b209-4368-b586-4d17842dfa19.jpg",
                            Price = 16.90m,
                            SnowflakeId = 317625235773854243L,
                            StockQuantity = 140,
                            Unit = "piece"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "蔬菜",
                            DisplayOrder = 1,
                            Icon = "🥬",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            Description = "水果",
                            DisplayOrder = 2,
                            Icon = "🍎",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            Description = "肉類",
                            DisplayOrder = 3,
                            Icon = "🥩",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 4,
                            Description = "海鮮",
                            DisplayOrder = 4,
                            Icon = "🐟",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 5,
                            Description = "乳製品",
                            DisplayOrder = 5,
                            Icon = "🥛",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "麵包/烘焙",
                            DisplayOrder = 6,
                            Icon = "🍞",
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 7,
                            Description = "飲料",
                            DisplayOrder = 7,
                            Icon = "🥤",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 8,
                            Description = "零食",
                            DisplayOrder = 8,
                            Icon = "🍿",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 9,
                            Description = "冷凍食品",
                            DisplayOrder = 9,
                            Icon = "❄️",
                            Name = "Frozen"
                        },
                        new
                        {
                            Id = 10,
                            Description = "家居用品",
                            DisplayOrder = 10,
                            Icon = "🏠",
                            Name = "Household"
                        },
                        new
                        {
                            Id = 11,
                            Description = "個人護理",
                            DisplayOrder = 11,
                            Icon = "🧴",
                            Name = "PersonalCare"
                        },
                        new
                        {
                            Id = 12,
                            Description = "其他",
                            DisplayOrder = 99,
                            Icon = "📦",
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductPromotion", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OverrideEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OverrideStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "PromotionId");

                    b.HasIndex("PromotionId");

                    b.ToTable("ProductPromotions");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PromotionId = 1,
                            Priority = 10
                        },
                        new
                        {
                            ProductId = 11,
                            PromotionId = 1,
                            OverrideEndDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OverrideStartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 10
                        },
                        new
                        {
                            ProductId = 6,
                            PromotionId = 2,
                            Priority = 20
                        },
                        new
                        {
                            ProductId = 12,
                            PromotionId = 2,
                            Priority = 20
                        },
                        new
                        {
                            ProductId = 7,
                            PromotionId = 3,
                            Priority = 5
                        },
                        new
                        {
                            ProductId = 13,
                            PromotionId = 3,
                            OverrideEndDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 5
                        },
                        new
                        {
                            ProductId = 8,
                            PromotionId = 4,
                            Priority = 1
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("AdminReplyAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AdminReplyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("IsDeleted", "CreatedAt")
                        .HasDatabaseName("IX_ProductReviews_IsDeleted_CreatedAt");

                    b.HasIndex("IsDeleted", "Status")
                        .HasDatabaseName("IX_ProductReviews_IsDeleted_Status");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("ProductId", "Status", "CreatedAt");

                    b.HasIndex("UserId", "ProductId", "OrderId")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("SupermarketMock.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FreeQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountValue = 20m,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Dairy 20% OFF",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "PercentageOff"
                        },
                        new
                        {
                            Id = 2,
                            DiscountValue = 15m,
                            EndDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Meat & Seafood Flash Sale",
                            StartDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "FixedDiscount"
                        },
                        new
                        {
                            Id = 3,
                            BuyQuantity = 2,
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FreeQuantity = 1,
                            Name = "Soft Drinks Buy 2 Get 1 FREE",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "BuyXGetYFree"
                        },
                        new
                        {
                            Id = 4,
                            BuyQuantity = 2,
                            DiscountValue = 25m,
                            EndDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snacks Bundle Offer",
                            StartDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "QuantitySpecialPrice"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.ReviewHelpful", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewHelpfuls");
                });

            modelBuilder.Entity("SupermarketMock.Models.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("SupermarketMock.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 2, 5, 53, 0, 325, DateTimeKind.Utc).AddTicks(8801),
                            Email = "admin@supermart.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$DO.m298rLnDRv5FmFP.AEeLNkG0/fqI2OXTA4O32QAGMC8dkyxhMm",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WishlistItems_CreatedAt");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Cart", b =>
                {
                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("SupermarketMock.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.CartItem", b =>
                {
                    b.HasOne("SupermarketMock.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupermarketMock.Models.CouponCategory", b =>
                {
                    b.HasOne("SupermarketMock.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Coupon", "Coupon")
                        .WithMany("CouponCategories")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("SupermarketMock.Models.CouponProduct", b =>
                {
                    b.HasOne("SupermarketMock.Models.Coupon", "Coupon")
                        .WithMany("CouponProducts")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupermarketMock.Models.CouponUsage", b =>
                {
                    b.HasOne("SupermarketMock.Models.Coupon", "Coupon")
                        .WithMany("CouponUsages")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.Order", b =>
                {
                    b.HasOne("SupermarketMock.Models.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.OrderItem", b =>
                {
                    b.HasOne("SupermarketMock.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupermarketMock.Models.Product", b =>
                {
                    b.HasOne("SupermarketMock.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductPromotion", b =>
                {
                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany("ProductPromotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Promotion", "Promotion")
                        .WithMany("ProductPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductReview", b =>
                {
                    b.HasOne("SupermarketMock.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.ReviewHelpful", b =>
                {
                    b.HasOne("SupermarketMock.Models.ProductReview", "Review")
                        .WithMany("HelpfulVotes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.ReviewImage", b =>
                {
                    b.HasOne("SupermarketMock.Models.ProductReview", "Review")
                        .WithMany("Images")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("SupermarketMock.Models.WishlistItem", b =>
                {
                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Coupon", b =>
                {
                    b.Navigation("CouponCategories");

                    b.Navigation("CouponProducts");

                    b.Navigation("CouponUsages");
                });

            modelBuilder.Entity("SupermarketMock.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Product", b =>
                {
                    b.Navigation("ProductPromotions");
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductReview", b =>
                {
                    b.Navigation("HelpfulVotes");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("SupermarketMock.Models.Promotion", b =>
                {
                    b.Navigation("ProductPromotions");
                });

            modelBuilder.Entity("SupermarketMock.Models.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
