// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermarketMock;

#nullable disable

namespace SupermarketMock.Migrations
{
    [DbContext(typeof(SupermarketContext))]
    [Migration("20260526094139_AddSubTotalOnOrderItemTable")]
    partial class AddSubTotalOnOrderItemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupermarketMock.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SupermarketMock.Models.CartItem", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SnowflakeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SnowflakeId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SupermarketMock.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<long>("SnowflakeId")
                        .HasColumnType("bigint");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SnowflakeId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Description = "Whole milk 1L",
                            IsAvailable = true,
                            Name = "Fresh Milk",
                            Photo = "milk.jpg",
                            Price = 22.90m,
                            SnowflakeId = 317625235773855528L,
                            StockQuantity = 120,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 6,
                            Description = "Fresh baked bread",
                            IsAvailable = true,
                            Name = "Whole Wheat Bread",
                            Photo = "bread.jpg",
                            Price = 18.50m,
                            SnowflakeId = 317625235773854947L,
                            StockQuantity = 80,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Description = "Farm fresh eggs",
                            IsAvailable = true,
                            Name = "Large Eggs (10pcs)",
                            Photo = "eggs.jpg",
                            Price = 28.00m,
                            SnowflakeId = 317625235773856039L,
                            StockQuantity = 65,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Sweet Japan Fuji apple",
                            IsAvailable = true,
                            Name = "Red Apple",
                            Photo = "apple.jpg",
                            Price = 15.90m,
                            SnowflakeId = 317625235773857742L,
                            StockQuantity = 200,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Philippine banana",
                            IsAvailable = true,
                            Name = "Banana",
                            Photo = "banana.jpg",
                            Price = 12.90m,
                            SnowflakeId = 317625235773855304L,
                            StockQuantity = 150,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "500g boneless",
                            IsAvailable = true,
                            Name = "Chicken Breast",
                            Photo = "chicken.jpg",
                            Price = 48.00m,
                            SnowflakeId = 317625235773856174L,
                            StockQuantity = 45,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Classic coke",
                            IsAvailable = true,
                            Name = "Coca Cola 1.25L",
                            Photo = "coke.jpg",
                            Price = 9.90m,
                            SnowflakeId = 317625235773855812L,
                            StockQuantity = 90,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Original flavor",
                            IsAvailable = true,
                            Name = "Potato Chips",
                            Photo = "chips.jpg",
                            Price = 14.50m,
                            SnowflakeId = 317625235773854539L,
                            StockQuantity = 110,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 12,
                            Description = "Thailand long grain",
                            IsAvailable = true,
                            Name = "White Rice 5kg",
                            Photo = "rice.jpg",
                            Price = 45.00m,
                            SnowflakeId = 317625235773856987L,
                            StockQuantity = 60,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Fresh red tomato",
                            IsAvailable = true,
                            Name = "Tomato",
                            Photo = "tomato.jpg",
                            Price = 8.90m,
                            SnowflakeId = 317625235773854504L,
                            StockQuantity = 180,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "150g cup",
                            IsAvailable = true,
                            Name = "Strawberry Yogurt",
                            Photo = "yogurt.jpg",
                            Price = 7.90m,
                            SnowflakeId = 317625235773856480L,
                            StockQuantity = 95,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "200g fresh salmon",
                            IsAvailable = true,
                            Name = "Salmon Fillet",
                            Photo = "salmon.jpg",
                            Price = 89.00m,
                            SnowflakeId = 317625235773857309L,
                            StockQuantity = 30,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Description = "1L 100% juice",
                            IsAvailable = true,
                            Name = "Orange Juice",
                            Photo = "orangejuice.jpg",
                            Price = 19.90m,
                            SnowflakeId = 317625235773854823L,
                            StockQuantity = 70,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 9,
                            Description = "500ml tub",
                            IsAvailable = true,
                            Name = "Ice Cream Vanilla",
                            Photo = "icecream.jpg",
                            Price = 35.00m,
                            SnowflakeId = 317625235773854877L,
                            StockQuantity = 55,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 11,
                            Description = "Colgate 100g",
                            IsAvailable = true,
                            Name = "Toothpaste",
                            Photo = "toothpaste.jpg",
                            Price = 16.90m,
                            SnowflakeId = 317625235773854243L,
                            StockQuantity = 140,
                            Unit = "piece"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "蔬菜",
                            DisplayOrder = 1,
                            Icon = "🥬",
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 2,
                            Description = "水果",
                            DisplayOrder = 2,
                            Icon = "🍎",
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            Description = "肉類",
                            DisplayOrder = 3,
                            Icon = "🥩",
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 4,
                            Description = "海鮮",
                            DisplayOrder = 4,
                            Icon = "🐟",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 5,
                            Description = "乳製品",
                            DisplayOrder = 5,
                            Icon = "🥛",
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "麵包/烘焙",
                            DisplayOrder = 6,
                            Icon = "🍞",
                            Name = "Bakery"
                        },
                        new
                        {
                            Id = 7,
                            Description = "飲料",
                            DisplayOrder = 7,
                            Icon = "🥤",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 8,
                            Description = "零食",
                            DisplayOrder = 8,
                            Icon = "🍿",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 9,
                            Description = "冷凍食品",
                            DisplayOrder = 9,
                            Icon = "❄️",
                            Name = "Frozen"
                        },
                        new
                        {
                            Id = 10,
                            Description = "家居用品",
                            DisplayOrder = 10,
                            Icon = "🏠",
                            Name = "Household"
                        },
                        new
                        {
                            Id = 11,
                            Description = "個人護理",
                            DisplayOrder = 11,
                            Icon = "🧴",
                            Name = "PersonalCare"
                        },
                        new
                        {
                            Id = 12,
                            Description = "其他",
                            DisplayOrder = 99,
                            Icon = "📦",
                            Name = "Others"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductPromotion", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OverrideEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OverrideStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "PromotionId");

                    b.HasIndex("PromotionId");

                    b.ToTable("ProductPromotions");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            PromotionId = 1,
                            Priority = 10
                        },
                        new
                        {
                            ProductId = 11,
                            PromotionId = 1,
                            OverrideEndDate = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OverrideStartDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 10
                        },
                        new
                        {
                            ProductId = 6,
                            PromotionId = 2,
                            Priority = 20
                        },
                        new
                        {
                            ProductId = 12,
                            PromotionId = 2,
                            Priority = 20
                        },
                        new
                        {
                            ProductId = 7,
                            PromotionId = 3,
                            Priority = 5
                        },
                        new
                        {
                            ProductId = 13,
                            PromotionId = 3,
                            OverrideEndDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 5
                        },
                        new
                        {
                            ProductId = 8,
                            PromotionId = 4,
                            Priority = 1
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyQuantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FreeQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountValue = 20m,
                            EndDate = new DateTime(2026, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Dairy 20% OFF",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "PercentageOff"
                        },
                        new
                        {
                            Id = 2,
                            DiscountValue = 15m,
                            EndDate = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Meat & Seafood Flash Sale",
                            StartDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "FixedDiscount"
                        },
                        new
                        {
                            Id = 3,
                            BuyQuantity = 2,
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FreeQuantity = 1,
                            Name = "Soft Drinks Buy 2 Get 1 FREE",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "BuyXGetYFree"
                        },
                        new
                        {
                            Id = 4,
                            BuyQuantity = 2,
                            DiscountValue = 25m,
                            EndDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snacks Bundle Offer",
                            StartDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "QuantitySpecialPrice"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 26, 9, 41, 39, 408, DateTimeKind.Utc).AddTicks(411),
                            Email = "admin@supermart.com",
                            PasswordHash = "$2a$11$6jZhESDnyEvP3nU/4HLDi.epkOpuT0YDJx4elZc72LmXlqdA8fc.O",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.Cart", b =>
                {
                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("SupermarketMock.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.CartItem", b =>
                {
                    b.HasOne("SupermarketMock.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupermarketMock.Models.Order", b =>
                {
                    b.HasOne("SupermarketMock.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupermarketMock.Models.OrderItem", b =>
                {
                    b.HasOne("SupermarketMock.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SupermarketMock.Models.Product", b =>
                {
                    b.HasOne("SupermarketMock.Models.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SupermarketMock.Models.ProductPromotion", b =>
                {
                    b.HasOne("SupermarketMock.Models.Product", "Product")
                        .WithMany("ProductPromotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupermarketMock.Models.Promotion", "Promotion")
                        .WithMany("ProductPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("SupermarketMock.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SupermarketMock.Models.Product", b =>
                {
                    b.Navigation("ProductPromotions");
                });

            modelBuilder.Entity("SupermarketMock.Models.Promotion", b =>
                {
                    b.Navigation("ProductPromotions");
                });

            modelBuilder.Entity("SupermarketMock.Models.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
