// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupermarketMock;

#nullable disable

namespace SupermarketMock.Migrations
{
    [DbContext(typeof(SupermarketContext))]
    [Migration("20260502050615_UpdateProductSeedData")]
    partial class UpdateProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupermarketMock.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 4,
                            Description = "Whole milk 1L",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Fresh Milk",
                            Photo = "milk.jpg",
                            Price = 22.90m,
                            StockQuantity = 120,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 2,
                            Category = 5,
                            Description = "Fresh baked bread",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Whole Wheat Bread",
                            Photo = "bread.jpg",
                            Price = 18.50m,
                            StockQuantity = 80,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 3,
                            Category = 4,
                            Description = "Farm fresh eggs",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Large Eggs (10pcs)",
                            Photo = "eggs.jpg",
                            Price = 28.00m,
                            StockQuantity = 65,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "Sweet Japan Fuji apple",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Red Apple",
                            Photo = "apple.jpg",
                            Price = 15.90m,
                            StockQuantity = 200,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Description = "Philippine banana",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Banana",
                            Photo = "banana.jpg",
                            Price = 12.90m,
                            StockQuantity = 150,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            Description = "500g boneless",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Chicken Breast",
                            Photo = "chicken.jpg",
                            Price = 48.00m,
                            StockQuantity = 45,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 7,
                            Category = 6,
                            Description = "Classic coke",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Coca Cola 1.25L",
                            Photo = "coke.jpg",
                            Price = 9.90m,
                            StockQuantity = 90,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 8,
                            Category = 7,
                            Description = "Original flavor",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Potato Chips",
                            Photo = "chips.jpg",
                            Price = 14.50m,
                            StockQuantity = 110,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 9,
                            Category = 11,
                            Description = "Thailand long grain",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "White Rice 5kg",
                            Photo = "rice.jpg",
                            Price = 45.00m,
                            StockQuantity = 60,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            Description = "Fresh red tomato",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Tomato",
                            Photo = "tomato.jpg",
                            Price = 8.90m,
                            StockQuantity = 180,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 11,
                            Category = 4,
                            Description = "150g cup",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Strawberry Yogurt",
                            Photo = "yogurt.jpg",
                            Price = 7.90m,
                            StockQuantity = 95,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 12,
                            Category = 3,
                            Description = "200g fresh salmon",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Salmon Fillet",
                            Photo = "salmon.jpg",
                            Price = 89.00m,
                            StockQuantity = 30,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 13,
                            Category = 6,
                            Description = "1L 100% juice",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Orange Juice",
                            Photo = "orangejuice.jpg",
                            Price = 19.90m,
                            StockQuantity = 70,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 14,
                            Category = 8,
                            Description = "500ml tub",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Ice Cream Vanilla",
                            Photo = "icecream.jpg",
                            Price = 35.00m,
                            StockQuantity = 55,
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 15,
                            Category = 10,
                            Description = "Colgate 100g",
                            IsAvailable = true,
                            IsOnSale = false,
                            Name = "Toothpaste",
                            Photo = "toothpaste.jpg",
                            Price = 16.90m,
                            StockQuantity = 140,
                            Unit = "piece"
                        });
                });

            modelBuilder.Entity("SupermarketMock.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
